config/routes.rb
Rails.application.routes.draw do
  get "/feed", to: "feed#index", as: "feed"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "articles#index"

  get "categories/:id", to: "categories#show", as: "category"

  post "friend", to: "friendships#friend", as: "friend"
  delete "unfriend", to: "friendships#unfriend", as: "unfriend"

  resources :users do
    resource :profile
  end

  get "/profiles", to: "profiles#index", as: "profiles"

  resources :articles do
    resources :comments
  end

  resources :messages, only:[:create]

  mount ActionCable.server => '/cable'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, :dependent => :destroy
  mount_uploader :avatar, AvatarUploader
  has_one :room
  has_many :messages

  after_create :create_chatroom

  def full_name
    "#{self.first_name}" + " " + "#{self.last_name}"
  end

  def name
    "#{self.first_name} #{self.last_name}".strip
  end

  private
  def create_chatroom
    hyphenated_username = self.full_name.split.join("-")
    Room.create(name: hyphenated_username, profile_id: self.id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  # before_action :only_current_user

  def index
    if params[:name] && params[:name] != ""
      names = params[:name].split(" ")
      f_name = "%#{names.first}%"
      l_name = "%#{names.last}%"
      @profiles = Profile.where("first_name LIKE ? OR last_name LIKE ?", f_name, l_name)
      if @profiles.count == 1
        redirect_to user_profile_path(@profiles.first)
      end
    else
      @profiles = Profile.all
    end
  end

  def new
    @user = find_user
    @profile = Profile.new
  end

  def create
    @user = find_user
    @profile = @user.build_profile(set_params)
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_profile_path( params[:user_id] )
    else
      render action: :new
    end
  end

  def show
    @user = find_user
    @users = User.all
    set_current_room
    @message = Message.new
    @messages = current_room.messages if current_room
    @friends = @user.all_friends
    @articles = current_user.get_feed
    @articles = @user.articles if @articles.empty?
  end

  def edit
    @user = find_user
    @profile = @user.profile
  end

  def update
    @user = find_user
    @profile = @user.profile
    if @profile.update(set_params)
      flash[:success] = "Profile Updated!"
      redirect_to user_profile_path( params[:user_id] )
    else
      render action: :edit
    end
  end


  private

  def only_current_user
    @user = find_user
    redirect_to(root_path) unless @user == current_user
  end

  def set_current_room
       # @room = current_user.profile.room
    if params[:room_id]
      @room = Room.find_by(id: params[:room_id])
    else
      @room = current_user.profile.room #this line of code may be my issue
    end
    session[:current_room] = @room.id if @room
  end

  def find_user
      User.find(params[:user_id])
  end

  def set_params
    params.require(:profile).permit(:first_name, :last_name, :bio, :avatar)
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path do |f| %>

<div class="form-group">
  <%= f.label :avatar %>
   <%= f.file_field :avatar %>
 </div>
 
<div class="form-group">
  <%= f.label :first_name %>
 <%= f.text_field :first_name, class: 'form-control' %>
</div>
<div class="form-group">
 <%= f.label :last_name %>
 <%= f.text_field :last_name, class: 'form-control' %>
</div>
<div class="form-group">
 <%= f.label :bio %>
 <%= f.text_area :bio, class: 'form-control' %>
</div>
<div class="form-group">
 <%= f.submit "Update Profile", class: 'btn btn-primary' %>
</div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center"> Edit Your Profile</h1>
      <p class="text-center">Become a memo author by filling out your profile!</p>
      <div class="well">


        <%= render "form" %>


      </div>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <h2>All Profiles</h2>

  <h3>Search By name:</h3>

  <%= form_tag profiles_path, method: :get do %>
  <%= text_field_tag :name %>
  <%= submit_tag 'Search' %>
  <% end %>

  <ul>
    <% @profiles.each do |profile| %>
    <li>
      <%= link_to profile.name, user_profile_path(profile) %>
    </li>
    <br>
    <% end %>
  </ul>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center"> Create Your Profile</h1>
      <p class="text-center">Become a memo author by filling out your profile!</p>
      <div class="well">
        <%= form_for @profile, url: user_profile_path do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
         <%= f.text_field :first_name, class: 'form-control' %>
       </div>
       <div class="form-group">
         <%= f.label :last_name %>
         <%= f.text_field :last_name, class: 'form-control' %>
       </div>
       <div class="form-group">
         <%= f.label :bio %>
         <%= f.text_area :bio, class: 'form-control' %>
       </div>
       <div class="form-group">
         <%= f.submit "Update Profile", class: 'btn btn-primary' %>
       </div>
        <% end %>




      </div>



    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">

<!-- In order to use the grid we must wrap everything inside of a row -->
  <div class="row">
      <div class="col-md-2 text-right">
        <% if @user.profile && @user.profile.avatar %>
          <%= image_tag(@user.profile.avatar_url(:thumb).to_s, class:"img-circle") %>
        <% end %>
        <br>
      </div>

    <div class="col-md-8 off-set 2 text-left">

      <h1> Name: <%= @user.profile.first_name %>
         <%= @user.profile.last_name %></h1>
         <% unless @user == current_user %>
            <% unless current_user.friends?(@user) %>
              <!-- <button type="button" name="button">Add Friend</button> -->
              <!-- <%= link_to "Add Friend", friend_path(@user) %> -->
              <%= button_to "Add Friend", friend_path(@user), :method => :post %>
            <% else %>
            <!-- <%= link_to "Unfriend", unfriend_path(@user) %> -->
            <%= button_to "Unfriend", unfriend_path(@user), :method => :delete %>

              <!-- <button type="button" name="button">Unfriend</button> -->
            <% end %>
            <br><br>
         <% end %>
         <div class="well">
          <strong>Bio: </strong> <%= @user.profile.bio %></p>
         </div>

         <hr>

         <div class="well">
          <h2>Friends</h2>
          Want to make new friends? <%= link_to "Click Here", profiles_path %>.
          <br>
          <% @friends.each do |user| %>
            <%= link_to user.profile.name, user_profile_path(user.id) %> <br>
          <% end %>
         </div>

         <div class="well">
           <%= render '/feed/index' %>
         </div>

         <div class="well">
          <div id=chat-window>
            <header> <%= current_room.profile.full_name  %>'s Chat </header>

          <div class="col-md-2">
            <% @friends.each do |friend| %>
                <%= link_to friend.profile.name, user_profile_path(current_user, roomId: friend.profile.room.id), class: 'friends' %>
              <% end %>
            <br>
          </div>

            <div id="chat-box" data-channel="rooms" data-room-id=<%= current_room.id %>>
              <% @messages.each do |message| %>
                  <br>
                <%= render partial: 'shared/message', locals: {message:message} %>
              <% end %>
            </div>

            <div id= "form-box">
              <%= form_for @message do |f| %>
                <%= f.text_field :body, id:'message-field', class: 'form-control pull-left'%>
                <%= f.submit 'Post', class: 'btn btn-default', id:'post-btn'%>

              <% end %>
            </div>

        </div>



         </div>
        </div>

     </div>
   </div>
  </div>
</div>