config/routes.rb
Rails.application.routes.draw do
  get "/feed", to: "feed#index", as: "feed"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "articles#index"

  get "categories/:id", to: "categories#show", as: "category"

  post "friend", to: "friendships#friend", as: "friend"
  delete "unfriend", to: "friendships#unfriend", as: "unfriend"

  resources :users do
    resource :profile
  end

  get "/profiles", to: "profiles#index", as: "profiles"

  resources :articles do
    resources :comments
  end

  resources :messages, only:[:create]

  mount ActionCable.server => '/cable'
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  default_scope {order(created_at: :desc)}

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories


  def categories_attributes=(attr)
    attr.each do |key, name|
      self.categories << Category.find_or_create_by(name) unless name[:name].empty?
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :find_id, only:[:show, :edit, :update, :destroy]

  def index
    @articles = Article.all

  end

  def new
    @article = Article.new
    @article.categories.build
    @article.categories.build
    @article.categories.build
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article has been created"
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been created"
      render :new
    end
  end

  def show
    @comment = @article.comments.build
    @comments = @article.comments
    @profile = @article.user.profile
  end

  def edit
    unless @article.user == current_user
      flash[:alert] = "You can only edit your own article"
      redirect_to root_path
    end
  end

  def update
    unless @article.user == current_user
      flash[:danger] = "You can only edit your own article"
      redirect_to root_path
    else
      if @article.update(article_params)
        flash[:success] = "Article has been updated"
        redirect_to @article
      else
        flash.now[:danger] = "Article has not been updated"
        render :edit
      end
    end
  end

  def destroy
    if @article.destroy
      flash[:success] = "Article has been deleted"
      redirect_to articles_path
    end

  end

  protected

    def resource_not_found
      message = "The article you are looking for could not be found"
      flash[:alert] = message
      redirect_to root_path
    end

  private

  def article_params
    params.require(:article).permit(:title, :body, categories_attributes: [:name])

  end

  def find_id
    @article = Article.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def persisted_comments(comments)
    comments.reject{|comment| comment.new_record?}
  end
end

app/views/articles/edit.html.erb
<div class="container">
  <h3 class="text-center">Editing new article</h3>

  <div class="row">
    <div class="col-md-12">
       <%= form_for @article, html: {class: "form-horizontal", role: "form"} do |f| %>
         <% if @article.errors.any?  %>
           <div class="panel panel-danger col-md-offset-1">
             <div class="panel-heading">
               <h2 class="panel-title">
                 <%= pluralize(@article.errors.count, "error") %>
                 - Sorry Michael prohibited this article from being saved
               </h2>
               <div class="panel-body">
                 <ul>
                   <% @article.errors.full_messages.each do |msg|  %>
                      <li>
                        <%= msg %>
                      </li>
                   <% end  %>
                 </ul>

               </div>
             </div>
           </div>
          <% end %>

          <div class="form-group">
            <div class="control-label col-md-1">
              <%= f.label :title %>
            </div>
            <div class="col-md-11">
              <%= f.text_field :title, class: 'form-control', placeholder:'Title of Article', autofocus: true %>
            </div>
          </div>

          <%= f.fields_for :categories do |cat| %>
          <div class="form-group">
            <div class="control-label col-md-1">
              <%= cat.label :name, "Category" %>
            </div>
            <div class="col-md-11">
              <%= cat.text_field :name, class: 'form-control', placeholder:'Name of Category', autofocus: true %><br>
            </div>
          </div>

          <% end %>

          <div class="form-group">
            <div class="control-label col-md-1">
              <%= f.label :body %>
            </div>
            <div class="col-md-11">
              <%= f.text_area :body, rows: 10, class: 'form-control', placeholder:'Body of Article', autofocus: true %>
            </div>
            <div class="form_group">
              <div class="col-md-offset-1 col-md-11">
                <br>
                <%= f.submit "Updated Article",  class: 'btn btn-primary btn-lg pull-right' %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">

  <% if user_signed_in? %>
  <% end  %>
  <p>Write your story, thoughts, or request here: <%= link_to "New Memo", new_article_path, class: "btn btn-default btn-lg", id: "new-article-btn" %></p>

  <% if @articles.empty? %>
    <h1 id="no-articles"> Be the First to Create A Memo Today?</h1>
  <% end  %>

  <% @articles.collect do |article| %>
    <div class="well well-md">
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
      </div>
      <div class="article-body">
        <%= truncate(article.body, length: 240) %>
      </div>
      <div class="author">
         <small>Created by: <%= link_to article.user.email, user_profile_path(article.user.id) %></small>
      </div>


    </div>

  <% end  %>


</div>

app/views/articles/new.html.erb
<div class="container">
  <h3 class="text-center">Sharing a new memo</h3>

  <div class="row">
    <div class="col-md-12">
       <%= form_for @article, html: {class: "form-horizontal", role: "form"} do |f| %>
         <% if @article.errors.any?  %>
           <div class="panel panel-danger col-md-offset-1">
             <div class="panel-heading">
               <h2 class="panel-title">
                 <%= pluralize(@article.errors.count, "error") %>
                 - Sorry prohibited this article from being saved
               </h2>
               <div class="panel-body">
                 <ul>
                   <% @article.errors.full_messages.each do |msg|  %>
                      <li>
                        <%= msg %>
                      </li>
                   <% end  %>
                 </ul>

               </div>
             </div>
           </div>
          <% end %>


          <div class="form-group">
            <div class="control-label col-md-1">
              <%= f.label :title %>
            </div>
            <div class="col-md-11">
              <%= f.text_field :title, class: 'form-control', placeholder:'Name of Memo', autofocus: true %>
            </div>
          </div>


          <%= f.fields_for :categories do |cat| %>
          <div class="form-group">
            <div class="control-label col-md-1">
              <%= cat.label :name, "Category" %>
            </div>
            <div class="col-md-11">
              <%= cat.text_field :name, class: 'form-control', placeholder:'Name of Category', autofocus: true %><br>
            </div>
          </div>

          <% end %>

          <div class="form-group">
            <div class="control-label col-md-1">
              <%= f.label :body %>
            </div>
            <div class="col-md-11">
              <%= f.text_area :body, rows: 10, class: 'form-control', placeholder:'Body of Memo', autofocus: true %>
            </div>
            <div class="form_group">
              <div class="col-md-offset-1 col-md-11">
                <br>
                <%= f.submit "Create Memo",  class: 'btn btn-primary btn-lg pull-right' %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <article class="detail-article">

    <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="article-detail-title" style="text-align: center;"><%= @article.title %></h1>
  </div>
</div>

    <div class="">
      <%= "Category".pluralize(@article.categories.count)+":" unless @article.categories.empty? %>
      <% @article.categories.each do |category| %>
        <span><%= link_to category.name, category_path(category) %></span>
      <% end %>
    </div>
    <br>
    <div class="glyphicon glyphicon-calendar" id="article-date">
      <%= @article.created_at.strftime("%b %d %Y") %>
    </div>

    <br><br>

    <div class="article-body">
      <%= @article.body %>
    </div>
    <br>

    <% if @profile %>
      <% if @profile.avatar %>
        <div class="">
         <%= image_tag(@profile.avatar_url(:thumb).to_s, class:"img-circle")   %>
        </div>
      <% end %>
      <small>Created by: <%= @profile.first_name%> <%= @profile.last_name%></small>
    <% end %>


    <% if user_signed_in? && current_user == @article.user %>
      <div class="edit-delete">
        <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-primary btn-lg btn-space pull-right"%>
        <%= link_to "Delete Article", article_path(@article), method: :delete, data:{confirm: "Are you sure you want to delete this article?"}, class: "btn btn-primary btn-lg btn-space pull-right" %>
      </div>
    <% end %>
    <br>
    <br>
</article>

  <hr>
  <div class="col-md-12">
    <%= form_for [@article, @comment ], remote: true,
:html => {class: "form-horizontal", role: "form"} do |f| %>
      <% if @comment.errors.any?  %>
          <div class="panel panel-danger col-md-offset-1">
            <div class="panel-heading">
              <h2 class="panel-title">
                <%= pluralize(@comment.errors.count, "error") %>
                prohibited this comment from being saved:
              </h2>
              <div class="panel-body">
                <ul>
                  <% @comment.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end  %>
                </ul>
              </div>
            </div>
          </div>
      <% end %>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :body, "New Comment" %>
        </div>
        <div class="col-md-10">
          <%= f.text_area :body, rows:10, class:'form-control', placeholder: 'Your comment', autoclear: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Add Comment", class: 'btn btn-primary btn-lg pull-right' %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <header>
      <h2>Comments</h2>
    </header>
    <div class="col-md-10">
      <% if @article.comments.any? %>
        <div id="messages">
          <% persisted_comments(@comments).each do |comment|%>
            <div class="comment-body">
              <%= comment.body %>
            </div>
            <div class="comment-time">
              <%= time_ago_in_words(comment.created_at) %>
              ago by <%= comment.user.email %>
            </div>
            <hr>
          <% end %>
        </div>
      <% else %>
      There are no comments to show
    <% end  %>
    </div>
  </div>

</div>