config/routes.rb
Rails.application.routes.draw do
  get "/feed", to: "feed#index", as: "feed"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "articles#index"

  get "categories/:id", to: "categories#show", as: "category"

  post "friend", to: "friendships#friend", as: "friend"
  delete "unfriend", to: "friendships#unfriend", as: "unfriend"

  resources :users do
    resource :profile
  end

  get "/profiles", to: "profiles#index", as: "profiles"

  resources :articles do
    resources :comments
  end

  resources :messages, only:[:create]

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  default_scope {order(created_at: :desc)}

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories


  def categories_attributes=(attr)
    attr.each do |key, name|
      self.categories << Category.find_or_create_by(name) unless name[:name].empty?
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :articles
  validates :name, presence: true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  validates :user_id, presence: true
  validates :friend_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :profile
  belongs_to :room
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, :dependent => :destroy
  mount_uploader :avatar, AvatarUploader
  has_one :room
  has_many :messages

  after_create :create_chatroom

  def full_name
    "#{self.first_name}" + " " + "#{self.last_name}"
  end

  def name
    "#{self.first_name} #{self.last_name}".strip
  end

  private
  def create_chatroom
    hyphenated_username = self.full_name.split.join("-")
    Room.create(name: hyphenated_username, profile_id: self.id)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :profile
  has_many :messages
end

app/models/user.rb
require 'faker'
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # before_save {self.email = email.downcase}
  has_many :articles
  has_one :profile
  after_create :setup_profile
  # validates :name, length:{maximum:20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,length:{maximum: 64},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  # Friends Actively
  has_many :friendships_active, class_name:  "Friendship", foreign_key: "user_id", dependent: :destroy
  has_many :friends, through: :friendships_active

  # Friends passively
  has_many :friendships_passive, class_name:  "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :users, through: :friendships_passive, class_name: "User"

  # All friends
  def all_friends
    users + friends
  end

  # Friends a user
  def friend(other_user)
    friends << other_user
  end

  # Unriends a user.
  def unfriend(other_user)
    friends.delete(other_user)
  end

  def get_feed
    @articles = Article.where(user_id: get_all_friends_ids)
  end

  def friendship(user)
    Friendship.where("(user_id = ? AND friend_id = ?) OR (user_id = ? AND friend_id = ?)",
      user.id, self.id, self.id, user.id).first
  end

  # Returns true if the current user is friends with the other user.
  def friends?(other_user)
    all_friends.include?(other_user)
  end

  private
  def setup_profile
    self.profile = Profile.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, bio: Faker::Lorem.paragraphs(4).join("\n"), user_id: self.id, avatar: Faker::Avatar.image)
  end

  def get_all_friends_ids
    ids = [self.id]
    self.all_friends.each do |friend|
      ids << friend.id
    end
    ids
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :find_id, only:[:show, :edit, :update, :destroy]

  def index
    @articles = Article.all

  end

  def new
    @article = Article.new
    @article.categories.build
    @article.categories.build
    @article.categories.build
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article has been created"
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been created"
      render :new
    end
  end

  def show
    @comment = @article.comments.build
    @comments = @article.comments
    @profile = @article.user.profile
  end

  def edit
    unless @article.user == current_user
      flash[:alert] = "You can only edit your own article"
      redirect_to root_path
    end
  end

  def update
    unless @article.user == current_user
      flash[:danger] = "You can only edit your own article"
      redirect_to root_path
    else
      if @article.update(article_params)
        flash[:success] = "Article has been updated"
        redirect_to @article
      else
        flash.now[:danger] = "Article has not been updated"
        render :edit
      end
    end
  end

  def destroy
    if @article.destroy
      flash[:success] = "Article has been deleted"
      redirect_to articles_path
    end

  end

  protected

    def resource_not_found
      message = "The article you are looking for could not be found"
      flash[:alert] = message
      redirect_to root_path
    end

  private

  def article_params
    params.require(:article).permit(:title, :body, categories_attributes: [:name])

  end

  def find_id
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article


  def create
    unless current_user
      flash[:alert] = "Please sign in or sign up first"
      redirect_to new_user_session_path
    else
      @comment = @article.comments.build(comment_params)
      @comment.user = current_user

      if @comment.save
        ActionCable.server.broadcast "comments",
          render(partial: 'comments/comment', object: @comment)
        flash[:notice] = "Comment has been created"
      else
        flash.now[:alert] = "Comment has not been created"
      end
      redirect_to article_path(@article)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = current_user.get_feed
    redirect_to articles_path if @articles.empty?  
  end
end

app/controllers/static_controller.rb
class StaticController < ActionController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  size = options[:size]
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.email,
                            class: "img-circle")
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def persisted_comments(comments)
    comments.reject{|comment| comment.new_record?}
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header role="banner">
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Meaning", root_path, class:"navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
            <% unless current_user.profile %>
              <li class="active"><%= link_to " Your Profile", new_user_profile_path(current_user) if current_user %></li>
              <% else %>
              <li><%= link_to "Edit Profile", edit_user_profile_path(current_user) if current_user %></li>
              <li ><%= link_to "Your Space", user_profile_path(current_user) if current_user %></li>
              <% end %>
              <p class="navbar-text">
                 <%= "Hello, #{current_user.email}" %>
                <li><%= link_to "Sign out", destroy_user_session_path, class: "btn btn-light", method: :delete %></li>
              </p>
        <% else %>
          <li ><%= link_to "Sign up", new_user_registration_path %></li>
          <li ><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>

      </ul>
    </div>

    <div class="container">
    </header>
    <% flash.each do |key,message| %>
      <div "text-center alert alert-primary <%= key == 'notice'? 'success': 'danger' %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/shared/_message.html.erb
<div class="message-row">

  <p class="message-body"> <%= message.body %></p>
  <span> <small> Posted by: <%= message.profile.full_name %></small></span>
</div>